name: hr-policy-rag-copilot
region: nyc

services:
  - name: backend
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    github:
      repo: Mkhan2317/hr-policy-rag-copilot
      branch: main
      deploy_on_push: true
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /api/health
    envs:
      - key: APP_ENV
        value: production
      - key: CORS_ORIGINS
        value: ${_self.PUBLIC_URL},${frontend.PUBLIC_URL}
      - key: OPENAI_API_KEY
        type: SECRET
      - key: TAVILY_API_KEY
        type: SECRET
      - key: PINECONE_API_KEY
        type: SECRET
      - key: PINECONE_INDEX_NAME
        value: fde-hr-policy-rag
      - key: PINECONE_NAMESPACE
        value: company-hr-kb
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: TOP_K
        value: "4"
      - key: MAX_RETRIES
        value: "1"
      - key: ADMIN_API_KEY
        type: SECRET

  - name: frontend
    dockerfile_path: frontend/Dockerfile
    source_dir: frontend
    github:
      repo: Mkhan2317/hr-policy-rag-copilot
      branch: main
      deploy_on_push: true
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${backend.PUBLIC_URL}
